# Promote NET-05 using only native source slides that contain editable text.
# Source slide 2 is deliberately excluded: it is a visual-only asset and its
# apparent overlap cannot be repaired without adding/rebuilding text objects.
$ErrorActionPreference='Stop'
$repo='C:\ppt-creater';$source=Join-Path $repo 'network-supplements\NET-05\travel-tourism-industry.pptx';$id='network-event-culture-tourism';$masterDir=Join-Path $repo ('network-production-library\'+$id);$valDir=Join-Path $repo ('network-production-library\validation\'+$id);$master=Join-Path $masterDir 'master.pptx';$val=Join-Path $valDir 'filled-validation.pptx';$catalog=Join-Path $repo 'catalog\network-production-template-library.json';New-Item -ItemType Directory -Force -Path $masterDir,$valDir|Out-Null;Copy-Item $source $master -Force;Copy-Item $master $val -Force
function Demo($old,$n){$a=@('文旅主题','核心资源','项目亮点','招商价值','发展路径','合作方向','市场机会','行动计划','城市名片','文化体验');$x=$a[($n-1)%$a.Count];$x.Substring(0,[math]::Min([math]::Max(2,$old.Length),$x.Length))}
$app=New-Object -ComObject PowerPoint.Application;$app.Visible=-1
try{
 $p=$app.Presentations.Open($val,$false,$false,$false);$slots=@();$pages=@();$retained=@();$fill=0;$before=0;for($s=1;$s -le $p.Slides.Count;$s++){$before+=$p.Slides.Item($s).TimeLine.MainSequence.Count}
 for($s=1;$s -le $p.Slides.Count;$s++){if($s -eq 2){continue};$page=@();for($i=1;$i -le $p.Slides.Item($s).Shapes.Count;$i++){$sh=$p.Slides.Item($s).Shapes.Item($i);$old='';$ok=$false;try{$ok=$sh.HasTextFrame -and $sh.TextFrame.HasText;if($ok){$old=$sh.TextFrame.TextRange.Text}}catch{};if($ok -and $old.Trim().Length -gt 1){$name=('slot_s{0:D2}_{1:D2}' -f $s,$i);$sh.Name=$name;$sh.TextFrame.TextRange.Text=(Demo $old ($fill+1));$it=[ordered]@{name=$name;shape_index=$i;max_chars_cn=$old.Length;animation_locked=$false};$slots+=$it;$page+=$it;$fill++}};if($page.Count -gt 0){$retained+=$s;$pages+=[ordered]@{source_slide_index=$s;slots=$page}}}
 $p.Save();$p.Close();$v=$app.Presentations.Open($val,$true,$false,$false);$after=0;for($s=1;$s -le $v.Slides.Count;$s++){$after+=$v.Slides.Item($s).TimeLine.MainSequence.Count};$play=$true;try{$v.SlideShowSettings.ShowType=2;$show=$v.SlideShowSettings.Run();Start-Sleep -Milliseconds 300;$show.View.GotoSlide(1,$true);Start-Sleep -Milliseconds 100;try{$show.View.Exit()}catch{}}catch{$play=$false};try{$v.Close()}catch{}
 $data=Get-Content $catalog -Raw|ConvertFrom-Json;$fam=[ordered]@{source_id='NET-05';source_pptx=$source;master_pptx=$master;validation_pptx=$val;route_targets=@('marketing-event','culture-tourism');slide_count=17;retained_source_slide_indices=$retained;semantic_slots=$slots;pages=$pages;fill_count=$fill;new_shapes=0;strict_native_only=$true;animation_effects_before=$before;animation_effects_after=$after;powerpoint_playback=$play;license_status='manual_external_review_required';native_overlap_repair=[ordered]@{source_slide_index=2;action='exclude_noneditable_visual_overlap_slide';new_shapes=0};status=if($play -and $before -eq $after -and $fill -gt 0){'production_ready'}else{'review_required'}};$data.families|Add-Member -Force -NotePropertyName $id -NotePropertyValue $fam;$data.overall_status=if(@($data.families.psobject.Properties|Where-Object {$_.Value.status -ne 'production_ready'}).Count -eq 0){'production_ready'}else{'review_required'};$data|ConvertTo-Json -Depth 12|Set-Content $catalog -Encoding utf8
}finally{try{$app.Quit()}catch{};try{[System.Runtime.Interopservices.Marshal]::ReleaseComObject($app)|Out-Null}catch{}}
Write-Output $catalog
