# Promote approved second-round network candidates as separate strict-native families.
$ErrorActionPreference='Stop'
$repo='C:\ppt-creater';$catalog=Join-Path $repo 'catalog\network-production-template-library.json'
$specs=@(
 @{id='network-investor-strategy';sourceId='NET-06';input='C:\ppt-creater\network-supplements\NET-06\medeley-business.pptx';targets=@('investor-pitch','ai-industry')},
 @{id='network-b2b-market-analysis';sourceId='NET-07';input='C:\ppt-creater\network-supplements\NET-07\marketing-analysis.pptx';targets=@('b2b-solution','brand-company-profile')},
 @{id='network-tech-product-workflow';sourceId='NET-08';input='C:\ppt-creater\network-supplements\NET-08\interface-file-folders.pptx';targets=@('technical-product','ai-industry')}
)
function Demo($old,$n){$a=@('战略判断','市场机会','客户价值','增长路径','产品能力','竞争壁垒','商业模式','融资计划','行动建议','技术路线','交付范围','客户案例');$x=$a[($n-1)%$a.Count];$x.Substring(0,[math]::Min([math]::Max(2,$old.Length),$x.Length))}
$data=Get-Content $catalog -Raw|ConvertFrom-Json
$app=New-Object -ComObject PowerPoint.Application;$app.Visible=-1
try{foreach($spec in $specs){$dir=Join-Path $repo ('network-production-library\'+$spec.id);$vdir=Join-Path $repo ('network-production-library\validation\'+$spec.id);New-Item -ItemType Directory -Force -Path $dir,$vdir|Out-Null;$master=Join-Path $dir 'master.pptx';$val=Join-Path $vdir 'filled-validation.pptx';Copy-Item $spec.input $master -Force;Copy-Item $master $val -Force;$p=$app.Presentations.Open($val,$false,$false,$false);$before=0;for($s=1;$s -le $p.Slides.Count;$s++){$before+=$p.Slides.Item($s).TimeLine.MainSequence.Count};$slides=$p.Slides.Count;$slots=@();$pages=@();$fill=0;for($s=1;$s -le $p.Slides.Count;$s++){$page=@();for($i=1;$i -le $p.Slides.Item($s).Shapes.Count;$i++){$sh=$p.Slides.Item($s).Shapes.Item($i);$old='';$ok=$false;try{$ok=$sh.HasTextFrame -and $sh.TextFrame.HasText;if($ok){$old=$sh.TextFrame.TextRange.Text}}catch{};if($ok -and $old.Trim().Length -gt 1){$name=('slot_s{0:D2}_{1:D2}' -f $s,$i);$sh.Name=$name;$sh.TextFrame.TextRange.Text=(Demo $old ($fill+1));$it=[ordered]@{name=$name;shape_index=$i;max_chars_cn=$old.Length;animation_locked=$false};$slots+=$it;$page+=$it;$fill++}};$pages+=[ordered]@{source_slide_index=$s;slots=$page}};$p.Save();$p.Close();$v=$app.Presentations.Open($val,$true,$false,$false);$after=0;for($s=1;$s -le $v.Slides.Count;$s++){$after+=$v.Slides.Item($s).TimeLine.MainSequence.Count};$play=$true;try{$v.SlideShowSettings.ShowType=2;$show=$v.SlideShowSettings.Run();Start-Sleep -Milliseconds 300;$show.View.GotoSlide(1,$true);Start-Sleep -Milliseconds 100;try{$show.View.Exit()}catch{}}catch{$play=$false};try{$v.Close()}catch{};$item=[ordered]@{source_id=$spec.sourceId;source_pptx=$spec.input;master_pptx=$master;validation_pptx=$val;route_targets=$spec.targets;slide_count=$slides;semantic_slots=$slots;pages=$pages;fill_count=$fill;new_shapes=0;strict_native_only=$true;animation_effects_before=$before;animation_effects_after=$after;powerpoint_playback=$play;license_status='manual_external_review_required';status=if($play -and $before -eq $after -and $fill -gt 0){'production_ready'}else{'review_required'}};$data.families|Add-Member -Force -NotePropertyName $spec.id -NotePropertyValue $item}
$data.overall_status=if(@($data.families.psobject.Properties|Where-Object {$_.Value.status -ne 'production_ready'}).Count -eq 0){'production_ready'}else{'review_required'};$data|ConvertTo-Json -Depth 12|Set-Content $catalog -Encoding utf8
}finally{try{$app.Quit()}catch{};try{[System.Runtime.Interopservices.Marshal]::ReleaseComObject($app)|Out-Null}catch{}}
Write-Output $catalog
